# Generated by Django 6.0.3 on 2026-03-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('against_bug', models.FloatField(default=1.0)),
                ('against_dark', models.FloatField(default=1.0)),
                ('against_dragon', models.FloatField(default=1.0)),
                ('against_electric', models.FloatField(default=1.0)),
                ('against_fairy', models.FloatField(default=1.0)),
                ('against_fight', models.FloatField(default=1.0)),
                ('against_fire', models.FloatField(default=1.0)),
                ('against_flying', models.FloatField(default=1.0)),
                ('against_ghost', models.FloatField(default=1.0)),
                ('against_grass', models.FloatField(default=1.0)),
                ('against_ground', models.FloatField(default=1.0)),
                ('against_ice', models.FloatField(default=1.0)),
                ('against_normal', models.FloatField(default=1.0)),
                ('against_poison', models.FloatField(default=1.0)),
                ('against_psychic', models.FloatField(default=1.0)),
                ('against_rock', models.FloatField(default=1.0)),
                ('against_steel', models.FloatField(default=1.0)),
                ('against_water', models.FloatField(default=1.0)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('abilities', models.ManyToManyField(related_name='pokemon_abilities', to='pokemon_app.ability')),
                ('type', models.ManyToManyField(related_name='pokemon_type', to='pokemon_app.pokemontype')),
            ],
        ),
    ]
