# Generated by Django 6.0.3 on 2026-03-08 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pokemon_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_slot_1', to='pokemon_app.pokemon')),
                ('pokemon_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_slot_2', to='pokemon_app.pokemon')),
                ('pokemon_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_slot_3', to='pokemon_app.pokemon')),
                ('pokemon_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_slot_4', to='pokemon_app.pokemon')),
                ('pokemon_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_slot_5', to='pokemon_app.pokemon')),
                ('pokemon_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_slot_6', to='pokemon_app.pokemon')),
            ],
        ),
    ]
