# Generated by Django 6.0.3 on 2026-03-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0002_pokemonteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonteam',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
