# Generated by Django 6.0.3 on 2026-03-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonteam',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
