# Generated by Django 6.0.3 on 2026-03-16 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0007_alter_ability_name_alter_pokemontype_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='against_fight',
            new_name='against_fighting',
        ),
        migrations.AlterField(
            model_name='pokemonteam',
            name='pokemon_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_slot_1', to='pokemon_app.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonteam',
            name='pokemon_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_slot_2', to='pokemon_app.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonteam',
            name='pokemon_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_slot_3', to='pokemon_app.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonteam',
            name='pokemon_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_slot_4', to='pokemon_app.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonteam',
            name='pokemon_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_slot_5', to='pokemon_app.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonteam',
            name='pokemon_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_slot_6', to='pokemon_app.pokemon'),
        ),
    ]
